name: 'data_warehouse'
version: '1.0.0'

profile: 'datawarehouse_profile'

# Set paths for your models
model-paths: ["models", "data_warehouse/models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_warehouse:  # Your project package
    raw:          # Raw models settings
      +materialized: table
    intermediate: # Intermediate models settings
      +materialized: table
    dwh:          # DWH models settings
      +materialized: table
